services:
  web:
    image: steel_web:${IMAGE_TAG}
    container_name: steel_web
    ports:
      - "5002:5000"
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg2://diana:20041902@host.docker.internal:5432/db
      FLASK_APP: "app:create_app"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
      FLASK_DEBUG: "0"
      command: flask run
    restart: unless-stopped

