services:


  web:
    # Важно: Jenkins сам соберёт image с нужным тегом
    image: steel_web:${IMAGE_TAG}
    container_name: steel_web
    env_file:
      - ../env
    environment:
      DATABASE_URL:
        ${DATABASE_URL}
    ports:
      - "5002:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
