"""empty message

Revision ID: 0253c4d17315
Revises: a563c655cf29
Create Date: 2025-08-27 14:11:40.645103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0253c4d17315'
down_revision = 'a563c655cf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sigma_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sigma_Cr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sigma_Mo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sigma_CrMo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hrc_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hrc_Ni', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hrc_Mn', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hrc_NiMn', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('T_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('T_drop', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('T_drop')
        batch_op.drop_column('T_base')
        batch_op.drop_column('hrc_NiMn')
        batch_op.drop_column('hrc_Mn')
        batch_op.drop_column('hrc_Ni')
        batch_op.drop_column('hrc_base')
        batch_op.drop_column('sigma_CrMo')
        batch_op.drop_column('sigma_Mo')
        batch_op.drop_column('sigma_Cr')
        batch_op.drop_column('sigma_base')

    # ### end Alembic commands ###
