"""empty message

Revision ID: 4747da37fe09
Revises: 0253c4d17315
Create Date: 2025-08-27 14:31:32.268912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4747da37fe09'
down_revision = '0253c4d17315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coef', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('T_base')
        batch_op.drop_column('sigma_CrMo')
        batch_op.drop_column('sigma_Mo')
        batch_op.drop_column('hrc_Mn')
        batch_op.drop_column('hrc_base')
        batch_op.drop_column('hrc_Ni')
        batch_op.drop_column('sigma_Cr')
        batch_op.drop_column('T_drop')
        batch_op.drop_column('sigma_base')
        batch_op.drop_column('hrc_NiMn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hrc_NiMn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sigma_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('T_drop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sigma_Cr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hrc_Ni', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hrc_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hrc_Mn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sigma_Mo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sigma_CrMo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('T_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('coef')

    # ### end Alembic commands ###
