"""empty message

Revision ID: 853bbee722b9
Revises: 
Create Date: 2025-08-26 19:34:07.486135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853bbee722b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('results_variant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'variants', ['variant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('results_variant_id_fkey'), 'variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###
