"""empty message

Revision ID: a563c655cf29
Revises: dbc31b255c0c
Create Date: 2025-08-26 19:50:47.815439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a563c655cf29'
down_revision = 'dbc31b255c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('results_variant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'variants', ['variant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('results_variant_id_fkey'), 'variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###
