"""initial schema

Revision ID: b2fe97d0fc08
Revises: 
Create Date: 2026-04-24 00:34:41.627043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2fe97d0fc08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigma_req', sa.Float(), nullable=True),
    sa.Column('hard_req', sa.Float(), nullable=True),
    sa.Column('t_req', sa.Float(), nullable=True),
    sa.Column('sum_limit', sa.Float(), nullable=True),
    sa.Column('interaction_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cr_min', sa.Float(), nullable=True),
    sa.Column('cr_max', sa.Float(), nullable=True),
    sa.Column('ni_min', sa.Float(), nullable=True),
    sa.Column('ni_max', sa.Float(), nullable=True),
    sa.Column('mo_min', sa.Float(), nullable=True),
    sa.Column('mo_max', sa.Float(), nullable=True),
    sa.Column('mn_min', sa.Float(), nullable=True),
    sa.Column('mn_max', sa.Float(), nullable=True),
    sa.Column('cost_cr', sa.Float(), nullable=True),
    sa.Column('cost_ni', sa.Float(), nullable=True),
    sa.Column('cost_mo', sa.Float(), nullable=True),
    sa.Column('cost_mn', sa.Float(), nullable=True),
    sa.Column('sigma_req', sa.Float(), nullable=True),
    sa.Column('hard_req', sa.Float(), nullable=True),
    sa.Column('t_req', sa.Float(), nullable=True),
    sa.Column('sum_max', sa.Float(), nullable=True),
    sa.Column('sum_min', sa.Float(), nullable=True),
    sa.Column('crni_max', sa.Float(), nullable=True),
    sa.Column('coef', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('cr', sa.Float(), nullable=True),
    sa.Column('ni', sa.Float(), nullable=True),
    sa.Column('mo', sa.Float(), nullable=True),
    sa.Column('mn', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('hardness', sa.Float(), nullable=True),
    sa.Column('t_melt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('req', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('variants')
    op.drop_table('users')
    op.drop_table('requirements')
    # ### end Alembic commands ###
