"""empty message

Revision ID: bcdb5e52c4cc
Revises: ad41e22eab8f
Create Date: 2025-08-28 12:28:50.712609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdb5e52c4cc'
down_revision = 'ad41e22eab8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sum_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sum_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crni_max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('crni_max')
        batch_op.drop_column('sum_min')
        batch_op.drop_column('sum_max')

    # ### end Alembic commands ###
