"""empty message

Revision ID: dbc31b255c0c
Revises: 853bbee722b9
Create Date: 2025-08-26 19:45:24.144734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc31b255c0c'
down_revision = '853bbee722b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('results_variant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'variants', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('results_variant_id_fkey'), 'variants', ['variant_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
